name: Publish Docsify site

on: [push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/docsify-action@master
      with:
        branch: main
        dir: docs-team
        github_token: ${{ secrets.GP_TOKEN }}
